export const faqDummyData = [
  {
    id: 1, categoryKey: "general",
    question: {
      en: "What is VoIP?", fr: "Qu'est-ce que la VoIP ?", ar: "ما هو VoIP؟",
      es: "¿Qué es VoIP?", ja: "VoIPとは何ですか？", de: "Was ist VoIP?",
      ko: "VoIP란 무엇인가요?", it: "Cos'è il VoIP?", "zh-CN": "什么是VoIP？",
    },
    answer: {
      en: "VoIP allows you to make voice and video calls over the internet instead of traditional phone lines, delivering crystal-clear audio at a fraction of the cost.",
      fr: "La VoIP permet de passer des appels vocaux et vidéo via Internet avec un son clair à moindre coût.",
      ar: "يتيح لك VoIP إجراء مكالمات صوتية ومرئية عبر الإنترنت بجودة عالية وتكلفة أقل.",
      es: "VoIP permite realizar llamadas de voz y video por internet con alta calidad y menor costo.",
      ja: "VoIPはインターネットを使って音声やビデオ通話を低コストで可能にします。",
      de: "VoIP ermöglicht Sprach- und Videoanrufe über das Internet zu geringeren Kosten.",
      ko: "VoIP는 인터넷을 통해 음성 및 영상 통화를 저렴하게 제공합니다.",
      it: "Il VoIP consente chiamate vocali e video via Internet a basso costo.",
      "zh-CN": "VoIP允许通过互联网进行语音和视频通话，成本更低。",
    },
  },
  {
    id: 2, categoryKey: "technical",
    question: {
      en: "How does VoIP work?", fr: "Comment fonctionne la VoIP ?", ar: "كيف يعمل VoIP؟",
      es: "¿Cómo funciona VoIP?", ja: "VoIPはどのように動作しますか？", de: "Wie funktioniert VoIP?",
      ko: "VoIP는 어떻게 작동하나요?", it: "Come funziona il VoIP?", "zh-CN": "VoIP是如何工作的？",
    },
    answer: {
      en: "Your voice is converted into digital packets and transmitted securely over the internet.",
      fr: "Votre voix est convertie en données numériques envoyées via Internet.",
      ar: "يتم تحويل الصوت إلى بيانات رقمية وإرسالها عبر الإنترنت.",
      es: "La voz se convierte en datos digitales enviados por internet.",
      ja: "音声はデジタルデータに変換されて送信されます。",
      de: "Sprache wird in digitale Daten umgewandelt.",
      ko: "음성은 디지털 데이터로 변환됩니다.",
      it: "La voce viene convertita in dati digitali.",
      "zh-CN": "语音被转换为数字数据传输。",
    },
  },
  {
    id: 3, categoryKey: "security",
    question: {
      en: "Is my data safe?", fr: "Mes données sont-elles sécurisées ?", ar: "هل بياناتي آمنة؟",
      es: "¿Mis datos están seguros?", ja: "データは安全ですか？", de: "Sind meine Daten sicher?",
      ko: "내 데이터는 안전한가요?", it: "I miei dati sono sicuri?", "zh-CN": "我的数据安全吗？",
    },
    answer: {
      en: "We use encryption and secure infrastructure to protect your data.",
      fr: "Nous utilisons le chiffrement pour sécuriser vos données.",
      ar: "نستخدم التشفير لحماية بياناتك.",
      es: "Usamos cifrado para proteger sus datos.",
      ja: "暗号化によりデータを保護します。",
      de: "Wir nutzen Verschlüsselung zum Schutz.",
      ko: "데이터는 암호화로 보호됩니다.",
      it: "Utilizziamo crittografia per protezione.",
      "zh-CN": "我们使用加密保护数据。",
    },
  },
  {
    id: 4, categoryKey: "account",
    question: {
      en: "Can I port my existing number?", fr: "Puis-je transférer mon numéro ?", ar: "هل يمكنني نقل رقمي؟",
      es: "¿Puedo portar mi número?", ja: "番号を移行できますか？", de: "Kann ich meine Nummer übertragen?",
      ko: "번호 이동이 가능한가요?", it: "Posso trasferire il numero?", "zh-CN": "可以转移号码吗？",
    },
    answer: {
      en: "Yes, you can transfer your number with no downtime.",
      fr: "Oui, transfert sans interruption.",
      ar: "نعم، بدون انقطاع.",
      es: "Sí, sin interrupciones.",
      ja: "はい、可能です。",
      de: "Ja, ohne Unterbrechung.",
      ko: "네, 가능합니다.",
      it: "Sì, senza interruzioni.",
      "zh-CN": "是的，可以。",
    },
  },
  {
    id: 5, categoryKey: "features",
    question: {
      en: "What features are included?", fr: "Quelles fonctionnalités sont incluses ?", ar: "ما الميزات المتوفرة؟",
      es: "¿Qué funciones incluye?", ja: "どんな機能がありますか？", de: "Welche Funktionen sind enthalten?",
      ko: "어떤 기능이 포함되나요?", it: "Quali funzionalità sono incluse?", "zh-CN": "包含哪些功能？",
    },
    answer: {
      en: "Includes HD calls, analytics, recording, and integrations.",
      fr: "Inclut appels HD, analyses et intégrations.",
      ar: "تشمل المكالمات والتحليلات والتكامل.",
      es: "Incluye llamadas HD y análisis.",
      ja: "通話、分析、統合機能。",
      de: "HD-Anrufe und Analysen.",
      ko: "통화 및 분석 포함.",
      it: "Chiamate e analisi incluse.",
      "zh-CN": "包括通话和分析。",
    },
  },
  {
    id: 6, categoryKey: "billing",
    question: {
      en: "Can I cancel anytime?", fr: "Puis-je annuler à tout moment ?", ar: "هل يمكنني الإلغاء في أي وقت؟",
      es: "¿Puedo cancelar en cualquier momento?", ja: "いつでも解約できますか？", de: "Kann ich jederzeit kündigen?",
      ko: "언제든 취소할 수 있나요?", it: "Posso annullare in qualsiasi momento?", "zh-CN": "可以随时取消吗？",
    },
    answer: {
      en: "Yes, no long-term contracts required.",
      fr: "Oui, aucun engagement.",
      ar: "نعم، بدون عقود.",
      es: "Sí, sin contratos.",
      ja: "はい、可能です。",
      de: "Ja, jederzeit.",
      ko: "네, 가능합니다.",
      it: "Sì, senza vincoli.",
      "zh-CN": "是的，没有合同。",
    },
  },
  {
    id: 7, categoryKey: "technical",
    question: {
      en: "What internet speed is required?", fr: "Quelle vitesse Internet est requise ?", ar: "ما سرعة الإنترنت المطلوبة؟",
      es: "¿Qué velocidad se necesita?", ja: "必要な速度は？", de: "Welche Geschwindigkeit wird benötigt?",
      ko: "필요한 속도는?", it: "Velocità richiesta?", "zh-CN": "需要多少网速？",
    },
    answer: {
      en: "At least 100 kbps per call.",
      fr: "100 kbps minimum.",
      ar: "100 كيلوبت/ث.",
      es: "100 kbps mínimo.",
      ja: "最低100kbps。",
      de: "Mindestens 100 kbps.",
      ko: "최소 100kbps.",
      it: "Minimo 100 kbps.",
      "zh-CN": "至少100kbps。",
    },
  },
  {
    id: 8, categoryKey: "general",
    question: {
      en: "Can I use VoIP on mobile?", fr: "Puis-je utiliser sur mobile ?", ar: "هل يعمل على الهاتف؟",
      es: "¿Funciona en móvil?", ja: "モバイルで使えますか？", de: "Mobil nutzbar?",
      ko: "모바일 사용 가능?", it: "Funziona su mobile?", "zh-CN": "可以在手机上用吗？",
    },
    answer: {
      en: "Yes, works on all devices.",
      fr: "Oui, sur tous appareils.",
      ar: "نعم، يعمل على كل الأجهزة.",
      es: "Sí, en todos los dispositivos.",
      ja: "はい、対応しています。",
      de: "Ja, auf allen Geräten.",
      ko: "네, 가능합니다.",
      it: "Sì, su tutti i dispositivi.",
      "zh-CN": "支持所有设备。",
    },
  },
  {
    id: 9, categoryKey: "features",
    question: {
      en: "Do you offer call recording?", fr: "Enregistrement des appels ?", ar: "هل يوجد تسجيل مكالمات؟",
      es: "¿Grabación de llamadas?", ja: "録音機能は？", de: "Anrufaufzeichnung?",
      ko: "통화 녹음 제공?", it: "Registrazione chiamate?", "zh-CN": "支持录音吗？",
    },
    answer: {
      en: "Yes, recording is available.",
      fr: "Oui, disponible.",
      ar: "نعم، متوفر.",
      es: "Sí, disponible.",
      ja: "はい。",
      de: "Ja.",
      ko: "네.",
      it: "Sì.",
      "zh-CN": "支持。",
    },
  },
  {
    id: 10, categoryKey: "security",
    question: {
      en: "Do you prevent fraud?", fr: "Prévention de fraude ?", ar: "هل تمنعون الاحتيال؟",
      es: "¿Previenen fraude?", ja: "不正防止は？", de: "Betrugsschutz?",
      ko: "사기 방지?", it: "Protezione frodi?", "zh-CN": "防诈骗吗？",
    },
    answer: {
      en: "Yes, we use monitoring systems.",
      fr: "Oui, systèmes de sécurité.",
      ar: "نعم، أنظمة حماية.",
      es: "Sí, sistemas de seguridad.",
      ja: "はい。",
      de: "Ja.",
      ko: "네.",
      it: "Sì.",
      "zh-CN": "是的。",
    },
  },
  {
    id: 11, categoryKey: "general",
    question: {
      en: "Why is VoIP better?", fr: "Pourquoi VoIP est mieux ?", ar: "لماذا VoIP أفضل؟",
      es: "¿Por qué es mejor?", ja: "なぜ優れている？", de: "Warum besser?",
      ko: "왜 더 좋은가요?", it: "Perché è migliore?", "zh-CN": "为什么更好？",
    },
    answer: {
      en: "Lower cost and more features.",
      fr: "Moins cher, plus de fonctions.",
      ar: "أرخص وأكثر ميزات.",
      es: "Más barato y funcional.",
      ja: "低コスト。",
      de: "Günstiger.",
      ko: "저렴함.",
      it: "Più economico.",
      "zh-CN": "更便宜。",
    },
  },
  {
    id: 12, categoryKey: "general",
    question: {
      en: "Who can use VoIP?", fr: "Qui peut utiliser ?", ar: "من يمكنه الاستخدام؟",
      es: "¿Quién puede usarlo?", ja: "誰が使える？", de: "Wer kann es nutzen?",
      ko: "누가 사용?", it: "Chi può usarlo?", "zh-CN": "谁可以使用？",
    },
    answer: {
      en: "Anyone including businesses and individuals.",
      fr: "Tous les utilisateurs.",
      ar: "الجميع.",
      es: "Todos.",
      ja: "誰でも。",
      de: "Jeder.",
      ko: "모두.",
      it: "Tutti.",
      "zh-CN": "所有人。",
    },
  },
  {
    id: 13, categoryKey: "general",
    question: {
      en: "Do I need special equipment?", fr: "Équipement spécial ?", ar: "هل أحتاج معدات؟",
      es: "¿Equipo especial?", ja: "特別な機器？", de: "Spezielle Geräte?",
      ko: "장비 필요?", it: "Serve attrezzatura?", "zh-CN": "需要设备吗？",
    },
    answer: {
      en: "No, just internet.",
      fr: "Non.",
      ar: "لا.",
      es: "No.",
      ja: "不要。",
      de: "Nein.",
      ko: "아니요.",
      it: "No.",
      "zh-CN": "不需要。",
    },
  },
  {
    id: 14, categoryKey: "general",
    question: {
      en: "Can I call internationally?", fr: "Appels internationaux ?", ar: "مكالمات دولية؟",
      es: "¿Llamadas internacionales?", ja: "国際通話？", de: "International?",
      ko: "국제전화?", it: "Internazionale?", "zh-CN": "国际电话？",
    },
    answer: {
      en: "Yes, at low cost.",
      fr: "Oui.",
      ar: "نعم.",
      es: "Sí.",
      ja: "はい。",
      de: "Ja.",
      ko: "네.",
      it: "Sì.",
      "zh-CN": "是的。",
    },
  },
  {
    id: 15, categoryKey: "general",
    question: {
      en: "Is it good for remote teams?", fr: "Télétravail ?", ar: "للعمل عن بعد؟",
      es: "¿Equipos remotos?", ja: "リモート向け？", de: "Remote geeignet?",
      ko: "원격 적합?", it: "Team remoto?", "zh-CN": "远程团队？",
    },
    answer: {
      en: "Yes, perfect for remote work.",
      fr: "Oui.",
      ar: "نعم.",
      es: "Sí.",
      ja: "はい。",
      de: "Ja.",
      ko: "네.",
      it: "Sì.",
      "zh-CN": "是的。",
    },
  },
  {
    id: 16, categoryKey: "general",
    question: {
      en: "How fast can I start?", fr: "Démarrage rapide ?", ar: "متى أبدأ؟",
      es: "¿Qué tan rápido inicio?", ja: "開始時間？", de: "Startzeit?",
      ko: "시작 시간?", it: "Avvio?", "zh-CN": "多久开始？",
    },
    answer: {
      en: "Within minutes.",
      fr: "En minutes.",
      ar: "خلال دقائق.",
      es: "En minutos.",
      ja: "数分。",
      de: "Minuten.",
      ko: "몇 분.",
      it: "Minuti.",
      "zh-CN": "几分钟。",
    },
  },
];